### ISSUE TITLE
gentlero/bitbucket-api version

### ISSUE THREAD

**Issue by ppelgrims** [GrahamCampbell/Laravel-Bitbucket#8]
This package is at version 1.0 at the moment, but the caret in composer.json prevents it from updating to this version. From the [docs](https://getcomposer.org/doc/articles/versions.md#caret-version-range-):

The `^` operator behaves very similarly but it sticks closer to semantic versioning, and will always allow non-breaking updates. For example `^1.2.3` is equivalent to `>=1.2.3 <2.0.0` as none of the releases until 2.0 should break backwards compatibility. For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`.

This is the recommended operator for maximum interoperability when writing library code.

Example: `^1.2.3`

Do you reckon we could update this package to that version?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch.

> The ^ operator behaves very similarly but it sticks closer to semantic versioning

Thanks, I know how that works. :) I didn't allow 1.x or 0.9.x since 0.x releases can have breaking changes, so I am using the `^` on purpose, locking into 0.8.x. However, I also didn't know there had been more releases beyond 0.8.x, so now that I know, I can inspect the changes, and decide if I can raise the upper bound.

> Do you reckon we could update this package to that version?

There aren't any breaking changes documented in the change log from 0.8.x to 1.x, so, I think the best option here would be to allow in 1.x too: https://github.com/GrahamCampbell/Laravel-Bitbucket/pull/9.

**Comment by ppelgrims** [comment]
Perfect!
